#!/usr/bin/env bash
# One-time, idempotent repository bootstrap for the SkillQuest / NurseQuest app.
# Installs Node dependencies, writes a local .env if missing, and provisions the
# local PostgreSQL database. The backend seeds sample data on first boot.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

# 1. Ensure PostgreSQL is installed (no-op if the base image already has it).
bash "$ROOT/.cursor/setup/ensure-postgres.sh"

# 2. Backend + frontend Node dependencies (uses each package's lockfile).
npm run install:all

# 3. Local environment file (git-ignored). Only created if absent so a
#    user-supplied .env always wins. JWT secret is random per environment.
if [ ! -f "$ROOT/.env" ]; then
  JWT_SECRET="$(openssl rand -hex 32 2>/dev/null || date +%s | sha256sum | cut -d' ' -f1)"
  cat > "$ROOT/.env" <<EOF
# Local development environment (generated by .cursor/setup/install.sh)
PORT=3001
NODE_ENV=development
DATABASE_URL=postgresql://nurse:nurse@127.0.0.1:5432/nursequest
JWT_SECRET=${JWT_SECRET}
CORS_ORIGINS=http://localhost:5173,http://localhost:5174
FRONTEND_URL=http://localhost:5173
EOF
  echo "Wrote $ROOT/.env"
fi

# 4. Bring up PostgreSQL and provision role/db/auth-shim.
bash "$ROOT/.cursor/setup/provision-db.sh"

echo "Install complete."
